server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    banner-mode: off
    log-startup-info: false

aws:
  region: eu-central-1
  postTable: Posts
