server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /microblog-service

spring:
  main:
    banner-mode: off
    log-startup-info: false

aws:
  region: ${AWS_REGION:eu-central-1}
  postTable: ${POST_TABLE:Posts}
